In [12]:
import numpy as np

### Array Fundamentals

In [13]:
# create a new list
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [14]:
type(my_list)

list

In [15]:
# create an ndarray using list 
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [16]:
type(my_array)

numpy.ndarray

In [17]:
# access array elements
my_array[1]

2

In [18]:
# ndarray is mutable, same as list
my_array[2] = 100
my_array

array([  1,   2, 100,   4,   5])

In [20]:
# like the original list, Python slice notation can be used for indexing
my_array[:3]

array([  1,   2, 100])

In [21]:
# One major difference is that slice indexing of a list "copies" the elements into a new list, 
# but slicing an array returns a "view": an object that refers to the data in the original array. 
# The original array can be mutated using the view.

array2 = my_array[3:]
array2

array([4, 5])

In [22]:
array2[0] = 200
array2

array([200,   5])

In [23]:
# original array also gets modified

my_array

array([  1,   2, 100, 200,   5])

In [24]:
# 2D list
my_list_2d = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
my_list_2d

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [25]:
# 2D ndarray
my_array_2d = np.array(my_list_2d)
my_array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
# list of lists elements can be accessed by specifying indices using 2 square brackets.

# my_list_2d[1,3]
my_list_2d[1][3]

8

In [29]:
# Difference between an array and a list of lists is that an element of the array can be accessed 
# by specifying the index along each axis within a single set of square brackets, separated by commas. 
# For instance, the element 8 is in row 1 and column 3:

my_array_2d[1, 3]

8

In [30]:
# We might hear of a 0-D (zero-dimensional) array referred to as a “scalar”, 
# a 1-D (one-dimensional) array as a “vector”, 
# a 2-D (two-dimensional) array as a “matrix”, 
# or an N-D (N-dimensional, where “N” is typically an integer greater than 2) array as a “tensor”. 

# For clarity, it is best to avoid the mathematical terms when referring to an array 
# because the mathematical objects with these names behave differently than arrays 
# (e.g. “matrix” multiplication is fundamentally different from “array” multiplication), 
# and there are other objects in the scientific Python ecosystem that have these names 
# (e.g. the fundamental data structure of PyTorch is the “tensor”).

### Array attributes

In [31]:
# lets discuss about array attributes: ndim, shape, size, dtype

In [32]:
# ndim
# The number of dimensions of an array is contained in the ndim attribute.

my_array_2d.ndim

2

In [33]:
my_array.ndim

1

In [34]:
# shape
# The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

my_array_2d.shape

(3, 4)

In [35]:
my_array.shape

(5,)

In [37]:
len(my_array_2d.shape) == my_array_2d.ndim

True

In [38]:
len(my_array.shape) == my_array.ndim

True

In [39]:
# size
# The fixed, total number of elements in array is contained in the size attribute.

my_array_2d.size

12

In [40]:
my_array.size

5

In [41]:
import math

In [42]:
my_array_2d.size == math.prod(my_array_2d.shape)

True

In [43]:
my_array.size == math.prod(my_array.shape)

True

In [44]:
# dtype
# Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. 
# The data type is recorded in the dtype attribute.

my_array_2d.dtype

dtype('int32')

In [45]:
my_array.dtype

dtype('int32')

### Create a basic array

In [46]:
# lets discuss about np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [47]:
# np.zeros()
# Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

np.zeros(3)

array([0., 0., 0.])

In [48]:
# np.ones()
# Besides creating an array from a sequence of elements, you can easily create an array filled with 1’s:

np.ones(3)

array([1., 1., 1.])

In [50]:
# np.empty()
# The function empty creates an array whose initial content is random and depends on the state of the memory. 
# The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

np.empty(3)

array([1., 1., 1.])

In [51]:
# np.arange()
# We can create an array with a range of elements:

np.arange(5)

array([0, 1, 2, 3, 4])

In [52]:
# And even an array that contains a range of evenly spaced intervals. 
# To do this, we will specify the first number, last number, and the step size.

np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [53]:
# np.linspace()
# We can use np.linspace() to create an array with values that are spaced linearly in a specified interval:

np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [54]:
np.linspace(0, 10, num=8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [56]:
# While the default data type is floating point (np.float64), 
# we can explicitly specify which data type we want using the dtype keyword.

x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

### Adding, removing, and sorting elements

In [57]:
# lets discuss np.sort(), np.concatenate()

In [58]:
# np.sort()
# Sorting an element is simple with np.sort(). 
# We can specify the axis, kind, and order when we call the function.

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [59]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
# np.concatenate()
# Used for concatenating 2 arrays

a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [61]:
b = np.array([5, 6, 7, 8])
b

array([5, 6, 7, 8])

In [62]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [64]:
y = np.array([[5, 6]])
y

array([[5, 6]])

In [65]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

### Reshape an array