In [9]:
import numpy as np

### Array Fundamentals

In [10]:
# create a new list
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [11]:
type(my_list)

list

In [12]:
# create an ndarray using list 
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [13]:
type(my_array)

numpy.ndarray

In [14]:
# access array elements
my_array[1]

2

In [15]:
# ndarray is mutable, same as list
my_array[2] = 100
my_array

array([  1,   2, 100,   4,   5])

In [16]:
# like the original list, Python slice notation can be used for indexing
my_array[:3]

array([  1,   2, 100])

In [17]:
# One major difference is that slice indexing of a list "copies" the elements into a new list, 
# but slicing an array returns a "view": an object that refers to the data in the original array. 
# The original array can be mutated using the view.

array2 = my_array[3:]
array2

array([4, 5])

In [18]:
array2[0] = 200
array2

array([200,   5])

In [19]:
# original array also gets modified

my_array

array([  1,   2, 100, 200,   5])

In [20]:
# 2D list
my_list_2d = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
my_list_2d

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [21]:
# 2D ndarray
my_array_2d = np.array(my_list_2d)
my_array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
# list of lists elements can be accessed by specifying indices using 2 square brackets.

# my_list_2d[1,3]
my_list_2d[1][3]

8

In [23]:
# Difference between an array and a list of lists is that an element of the array can be accessed 
# by specifying the index along each axis within a single set of square brackets, separated by commas. 
# For instance, the element 8 is in row 1 and column 3:

my_array_2d[1, 3]

8

In [24]:
# We might hear of a 0-D (zero-dimensional) array referred to as a “scalar”, 
# a 1-D (one-dimensional) array as a “vector”, 
# a 2-D (two-dimensional) array as a “matrix”, 
# or an N-D (N-dimensional, where “N” is typically an integer greater than 2) array as a “tensor”. 

# For clarity, it is best to avoid the mathematical terms when referring to an array 
# because the mathematical objects with these names behave differently than arrays 
# (e.g. “matrix” multiplication is fundamentally different from “array” multiplication), 
# and there are other objects in the scientific Python ecosystem that have these names 
# (e.g. the fundamental data structure of PyTorch is the “tensor”).

### Array attributes

In [25]:
# lets discuss about array attributes: ndim, shape, size, dtype

In [26]:
# ndim
# The number of dimensions of an array is contained in the ndim attribute.

my_array_2d.ndim

2

In [27]:
my_array.ndim

1

In [28]:
# shape
# The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

my_array_2d.shape

(3, 4)

In [29]:
my_array.shape

(5,)

In [30]:
len(my_array_2d.shape) == my_array_2d.ndim

True

In [31]:
len(my_array.shape) == my_array.ndim

True

In [32]:
# size
# The fixed, total number of elements in array is contained in the size attribute.

my_array_2d.size

12

In [33]:
my_array.size

5

In [34]:
import math

In [35]:
my_array_2d.size == math.prod(my_array_2d.shape)

True

In [36]:
my_array.size == math.prod(my_array.shape)

True

In [37]:
# dtype
# Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. 
# The data type is recorded in the dtype attribute.

my_array_2d.dtype

dtype('int32')

In [38]:
my_array.dtype

dtype('int32')

### Create a basic array

In [39]:
# lets discuss about np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [40]:
# np.zeros()
# Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

np.zeros(3)

array([0., 0., 0.])

In [41]:
# np.ones()
# Besides creating an array from a sequence of elements, you can easily create an array filled with 1’s:

np.ones(3)

array([1., 1., 1.])

In [42]:
# np.empty()
# The function empty creates an array whose initial content is random and depends on the state of the memory. 
# The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

np.empty(3)

array([1., 1., 1.])

In [43]:
# np.arange()
# We can create an array with a range of elements:

np.arange(5)

array([0, 1, 2, 3, 4])

In [44]:
# And even an array that contains a range of evenly spaced intervals. 
# To do this, we will specify the first number, last number, and the step size.

np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [45]:
# np.linspace()
# We can use np.linspace() to create an array with values that are spaced linearly in a specified interval:

np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [46]:
np.linspace(0, 10, num=8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [47]:
# While the default data type is floating point (np.float64), 
# we can explicitly specify which data type we want using the dtype keyword.

x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

### Adding, removing, and sorting elements

In [48]:
# lets discuss np.sort(), np.concatenate()

In [49]:
# np.sort()
# Sorting an element is simple with np.sort(). 
# We can specify the axis, kind, and order when we call the function.

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [50]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
# np.concatenate()
# Used for concatenating 2 arrays

a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [52]:
b = np.array([5, 6, 7, 8])
b

array([5, 6, 7, 8])

In [53]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [55]:
y = np.array([[5, 6]])
y

array([[5, 6]])

In [56]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

### Reshape an array

In [58]:
# reshape()
# Using arr.reshape() will give a new shape to an array without changing the data. 
# Just remember that when we use the reshape method, the array we want to produce needs to have 
# the same number of elements as the original array. 
# If you start with an array with 12 elements, we’ll need to make sure that 
# our new array also has a total of 12 elements.

In [59]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [60]:
# we can reshape this array to an array with three rows and two columns:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

### Convert 1D array to 2D array

In [61]:
# lets discuss about np.newaxis, np.expand_dims

In [62]:
# np.newaxis
# This will increase the dimensions of our array by one dimension when used once.
# This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [63]:
a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [64]:
a.shape

(6,)

In [65]:
# We can convert a 1D array to a row vector by inserting an axis along the first dimension:

row_vector = a[np.newaxis, :]
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [66]:
row_vector.shape

(1, 6)

In [67]:
# for a column vector, we can insert an axis along the second dimension:

col_vector = a[:, np.newaxis]
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [68]:
col_vector.shape

(6, 1)

In [69]:
# np.expand_dims
# We can also expand an array by inserting a new axis at a specified position

In [70]:
a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [71]:
a.shape

(6,)

In [74]:
# We can use np.expand_dims to add an axis at index position 0 with:

b = np.expand_dims(a, axis=0)
b

array([[1, 2, 3, 4, 5, 6]])

In [75]:
b.shape

(1, 6)

In [76]:
# similarly for index position 1:

c = np.expand_dims(a, axis=1)
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [77]:
c.shape

(6, 1)

### Indexing and Slicing